nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  "@chakra-ui/react@^2.2.9":
    dependencies:
      "@chakra-ui/styled-system": "^2.2.8"
  "@chakra-ui/toast@^3.0.7":
    dependencies:
      "@chakra-ui/styled-system": "^2.2.8"
