name: demo

on:
  workflow_dispatch:
    branches: [main]
  release:
    branches: [main]

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build everything
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: packages/demo/dist
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY }}
