name: publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Test Website Build
        working-directory: ./website
        run: |
          yarn install --immutable
          yarn build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release Website to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        working-directory: ./website
        run: |
          git config --global user.email "jakeboone02@gmail.com"
          git config --global user.name "Jake Boone"
          yarn install --immutable
          yarn deploy
