name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          dry: true
          prettier_options: --check "*.js" "examples/**/*" "packages/*/src/**" "packages/*/dev/**" "website/*.js" "website/{docs,src,versioned_docs,versioned_sidebars}/**"
          prettier_version: 2.7.1
          prettier_plugins: prettier-plugin-organize-imports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  # test-types:
  #   name: Test Types with TypeScript ${{ matrix.ts }}

  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       node: ['16.x']
  #       ts: ['4.1', '4.5', 'latest']
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Use node ${{ matrix.node }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: 'yarn'

  #     - name: Install Dependencies and Build with Latest TypeScript
  #       run: |
  #         yarn install
  #         yarn build

  #     - name: Install TypeScript ${{ matrix.ts }} in Demo and Test
  #       run: |
  #         yarn workspace @react-querybuilder/demo add -D typescript@${{ matrix.ts }}
  #         yarn workspace @react-querybuilder/demo tsc --version
  #         yarn tsc --version
  #         yarn workspace @react-querybuilder/demo typecheck
