name: Website publish

on:
  pull_request:
    paths:
      - 'website/**'
  push:
    branches: [main]
    paths:
      - 'website/**'

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install website dependencies
        run: yarn --immutable
        working-directory: website
      - name: Build Website
        run: yarn build
        working-directory: website

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install website dependencies
        run: yarn --immutable
        working-directory: website
      - name: Build Website
        run: yarn build
        working-directory: website
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_WEBSITE_DEPLOY }}
      - name: Deploy Website to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "jakeboone02@gmail.com"
          git config --global user.name "Jake Boone"
          cd website && yarn deploy
